/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.quanlythuvien;

import java.sql.Connection;
import java.sql.Date;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.time.LocalDate;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.JTable;

/**
 *
 * @author khang
 */
public class quanlithuvienap extends javax.swing.JFrame {
    
    DefaultTableModel model;
    DefaultTableModel model1;
    DefaultTableModel model2;
       
    List<Sinhvien> sinhvienList = new ArrayList<>();
    List<Sach> sachList = new ArrayList<>();
    List<Phieumuon> phieumuonList = new ArrayList<>();
   
    public quanlithuvienap() {
        initComponents();
         model = (DefaultTableModel) hienthi.getModel();
        model1 = (DefaultTableModel) hienthi2.getModel();
        model2 = (DefaultTableModel) hienthi3.getModel();
        
     showSinhvien();
        showSach();
          showPhieumuon();
    }

     private void showSinhvien(){
         sinhvienList = SinhvienModify.findAll();
        model1.setRowCount(0);
        for(Sinhvien sinhvien : sinhvienList){
            model1.addRow(new Object[] {model1.getRowCount()+1,
            sinhvien.getMsv(),
            sinhvien.getTensv(),
            sinhvien.getDiachi(),
            sinhvien.getSdt(),
            sinhvien.getEmail()} );
        }
    }
     
     
  private void showPhieumuon() {
    phieumuonList = PhieumuonModify.findAll();
    model2.setRowCount(0);
    for (Phieumuon phieumuon : phieumuonList) {
        Sinhvien sinhvien = SinhvienModify.findSinhvienById(phieumuon.getMsv_muon());
        Sach sach = SachModify.findSachById(phieumuon.getId_sach());
        model2.addRow(new Object[]{
            model2.getRowCount() + 1,
            phieumuon.getMaphieumuon(),
            phieumuon.getMsv_muon(),
            sinhvien.getTensv(),
            phieumuon.getId_sach(),
            sach.getTensach(),
            phieumuon.getNgaymuon(),
            phieumuon.getNgayphaitra(),
            phieumuon.getNgaytra(),
            phieumuon.getSongaymuon(),
            phieumuon.getTrangthaimuon()
        });
    }
}

     
       private void showSach(){
         sachList = SachModify.findAll();
        model.setRowCount(0);
        for(Sach sach : sachList){
            model.addRow(new Object[] {model.getRowCount()+1,
            sach.getId(),
            sach.getTensach(),
            sach.getTacgia(),
            sach.getTheloai(),
            sach.getSoluong(),
           } );
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        hienthibandoc = new javax.swing.JTabbedPane();
        jPanel4 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        txtMsv = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        txtTensv = new javax.swing.JTextField();
        txtDiachi = new javax.swing.JTextField();
        txtSdt = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        btnThem4 = new javax.swing.JButton();
        btnSua4 = new javax.swing.JButton();
        btnLuu4 = new javax.swing.JButton();
        btnXoa4 = new javax.swing.JButton();
        btnHuy4 = new javax.swing.JButton();
        jScrollPane6 = new javax.swing.JScrollPane();
        hienthi2 = new javax.swing.JTable();
        btntim2 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        txtTensach = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        txtTacgia = new javax.swing.JTextField();
        txtTheloai = new javax.swing.JTextField();
        txtSoluong = new javax.swing.JTextField();
        btnThem1 = new javax.swing.JButton();
        btnSua1 = new javax.swing.JButton();
        btnLuu1 = new javax.swing.JButton();
        btnXoa1 = new javax.swing.JButton();
        btnHuy1 = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        hienthi = new javax.swing.JTable();
        btnTim1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtMsvm = new javax.swing.JTextField();
        txtMsm = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        hienthi3 = new javax.swing.JTable();
        btnthem3 = new javax.swing.JButton();
        btnsua3 = new javax.swing.JButton();
        btnluu3 = new javax.swing.JButton();
        btnxoa3 = new javax.swing.JButton();
        btnTrasach = new javax.swing.JButton();
        btntim3 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtTst = new javax.swing.JTextField();
        txtTsdg = new javax.swing.JTextField();
        txtTsm = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        btn_thongke = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        txtTslc = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtMtn = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtTsstn = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtM1t = new javax.swing.JTextField();
        txtT1t = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        txtquahan = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel22.setText("Mã Sinh Viên :");

        jLabel23.setText("Họ và Tên :");

        jLabel24.setText("Địa Chỉ :");

        jLabel25.setText("Số Điện Thoại :");

        jLabel26.setText("Email :");

        btnThem4.setText("Thêm");
        btnThem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThem4ActionPerformed(evt);
            }
        });

        btnSua4.setText("Sửa");
        btnSua4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSua4ActionPerformed(evt);
            }
        });

        btnLuu4.setText("Lưu");
        btnLuu4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLuu4ActionPerformed(evt);
            }
        });

        btnXoa4.setText("Xóa");
        btnXoa4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoa4ActionPerformed(evt);
            }
        });

        btnHuy4.setText("Hủy");
        btnHuy4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHuy4ActionPerformed(evt);
            }
        });

        hienthi2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "STT", "Mã Sinh Viên", "Họ và Tên", "Địa Chỉ", "Số Điện Thoại", "Email"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane6.setViewportView(hienthi2);

        btntim2.setText("Tra cứu");
        btntim2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btntim2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtSdt, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtDiachi, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtTensv, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtMsv)
                            .addComponent(txtEmail, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane6))
                        .addGap(70, 70, 70))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(btnThem4, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                        .addComponent(btnSua4, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(53, 53, 53)
                        .addComponent(btnLuu4, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(63, 63, 63)
                        .addComponent(btnXoa4, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(60, 60, 60)
                        .addComponent(btnHuy4, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(54, 54, 54)
                        .addComponent(btntim2, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(147, 147, 147))))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel22)
                    .addComponent(txtMsv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTensv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel23))
                .addGap(18, 18, 18)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDiachi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel24))
                .addGap(18, 18, 18)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSdt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel25))
                .addGap(18, 18, 18)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel26)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnThem4)
                    .addComponent(btnSua4)
                    .addComponent(btnLuu4)
                    .addComponent(btnXoa4)
                    .addComponent(btnHuy4)
                    .addComponent(btntim2))
                .addContainerGap(106, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 136, Short.MAX_VALUE))
        );

        hienthibandoc.addTab("Quản lý bạn đọc", jPanel4);

        jLabel12.setText("Tên Sách :");

        jLabel13.setText("Tác Giả :");

        jLabel14.setText("Thể Loại :");

        jLabel15.setText("Số Lượng :");

        btnThem1.setText("Thêm");
        btnThem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThem1ActionPerformed(evt);
            }
        });

        btnSua1.setText("Sửa");
        btnSua1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSua1ActionPerformed(evt);
            }
        });

        btnLuu1.setText("Lưu");
        btnLuu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLuu1ActionPerformed(evt);
            }
        });

        btnXoa1.setText("Xóa");
        btnXoa1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoa1ActionPerformed(evt);
            }
        });

        btnHuy1.setText("Hủy");
        btnHuy1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHuy1ActionPerformed(evt);
            }
        });

        hienthi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "STT", "Id", "Tên Sách", "Tác Giả", "Thể Loại", "Số Lượng"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane4.setViewportView(hienthi);

        btnTim1.setText("Tra cứu");
        btnTim1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTim1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 664, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
                            .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(39, 39, 39)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                                .addComponent(btnThem1, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(24, 24, 24)
                                .addComponent(btnSua1, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(24, 24, 24)
                                .addComponent(btnLuu1, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(27, 27, 27)
                                .addComponent(btnXoa1, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(17, 17, 17)
                                .addComponent(btnHuy1, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnTim1, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(8, 8, 8))
                            .addComponent(txtTheloai, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtTacgia)
                            .addComponent(txtTensach)
                            .addComponent(txtSoluong, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addContainerGap(456, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(76, Short.MAX_VALUE)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(txtTensach, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(txtTacgia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(txtTheloai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel15)
                    .addComponent(txtSoluong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnThem1)
                    .addComponent(btnSua1)
                    .addComponent(btnTim1)
                    .addComponent(btnHuy1)
                    .addComponent(btnLuu1)
                    .addComponent(btnXoa1))
                .addGap(81, 81, 81))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 136, Short.MAX_VALUE))
        );

        hienthibandoc.addTab("Quản lý sách", jPanel2);

        jLabel1.setText("Mã Sinh Viên :");

        jLabel2.setText("Mã Sách Mượn :");

        txtMsvm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMsvmActionPerformed(evt);
            }
        });

        hienthi3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "STT", "Mã Mượn", "Mã Sinh Viên", "Tên Sinh Viên", "Mã Sách Mượn", "Tên Sách", "Ngày Mượn", "Hạn Trả Sách", "Ngày Trả", "Số Ngày Mượn", "Trạng Thái"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(hienthi3);

        btnthem3.setText("Thêm");
        btnthem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnthem3ActionPerformed(evt);
            }
        });

        btnsua3.setText("Chọn");
        btnsua3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsua3ActionPerformed(evt);
            }
        });

        btnluu3.setText("Lưu");
        btnluu3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnluu3ActionPerformed(evt);
            }
        });

        btnxoa3.setText("Xóa");
        btnxoa3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnxoa3ActionPerformed(evt);
            }
        });

        btnTrasach.setText("Trả Sách");
        btnTrasach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTrasachActionPerformed(evt);
            }
        });

        btntim3.setText("Tra Cứu");
        btntim3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btntim3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 745, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(btnthem3, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnsua3, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnluu3, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnxoa3, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnTrasach, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btntim3, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 132, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(txtMsm, javax.swing.GroupLayout.DEFAULT_SIZE, 607, Short.MAX_VALUE)
                                    .addComponent(txtMsvm))))))
                .addContainerGap(475, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(81, 81, 81)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtMsvm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtMsm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnthem3)
                    .addComponent(btnxoa3)
                    .addComponent(btnTrasach)
                    .addComponent(btntim3)
                    .addComponent(btnluu3)
                    .addComponent(btnsua3))
                .addContainerGap(211, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        hienthibandoc.addTab("Quản lý mượn", jPanel1);

        jLabel4.setText("Tổng Số Đầu Sách Trong Kho :");

        jLabel5.setText("Tổng Số Độc Giả :");

        jLabel6.setText("Tổng Số Sách Đang Được Mượn :");

        txtTst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTstActionPerformed(evt);
            }
        });

        txtTsdg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTsdgActionPerformed(evt);
            }
        });

        txtTsm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTsmActionPerformed(evt);
            }
        });

        jLabel7.setText("Thống Kê Số Liệu");

        btn_thongke.setText("Làm Mới");
        btn_thongke.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_thongkeActionPerformed(evt);
            }
        });

        jLabel8.setText("Số Lượng Sách Còn Trong Kho :");

        txtTslc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTslcActionPerformed(evt);
            }
        });

        jLabel3.setText("Tổng Số Sách Được Mượn Trong Ngày :");

        jLabel9.setText("Tổng Số Sách Được Trả Trong Ngày :");

        jLabel10.setText("Tổng Sô Sách Được Mượn Trong 30 Ngày : ");

        jLabel11.setText("Tổng Sô Sách Được Trả Trong 30 Ngày : ");

        jLabel16.setText("Tổng Số Sách Quá Hạn :");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(233, 233, 233)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(41, 41, 41)
                                .addComponent(txtquahan, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 262, Short.MAX_VALUE)
                                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 226, Short.MAX_VALUE))
                                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, 262, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtTsdg, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtTsm, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtTst, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtTslc, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtMtn, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtTsstn, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtM1t, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtT1t, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(831, 831, 831))))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(317, 317, 317)
                .addComponent(btn_thongke)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtTslc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtTst, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtTsdg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtTsm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(txtMtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(txtTsstn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(txtM1t, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel16))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(txtT1t, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtquahan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(24, 24, 24)
                .addComponent(btn_thongke)
                .addContainerGap(156, Short.MAX_VALUE))
        );

        hienthibandoc.addTab("Thông kê", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(hienthibandoc, javax.swing.GroupLayout.PREFERRED_SIZE, 1259, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(hienthibandoc, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 665, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtTslcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTslcActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTslcActionPerformed

    private void btn_thongkeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_thongkeActionPerformed
       try {
        // Kết nối đến cơ sở dữ liệu
        Connection connection = DriverManager.getConnection("jdbc:mysql://localhost:3306/qltvap", "root", "");

        // Lấy tổng số sinh viên
        String query1 = "SELECT COUNT(*) AS total FROM sinhvien";
        try (Statement statement = connection.createStatement();
             ResultSet resultSet1 = statement.executeQuery(query1)) {
            // Xử lý kết quả
            if (resultSet1.next()) {
                int totalSinhVien = resultSet1.getInt("total");
                txtTsdg.setText(Integer.toString(totalSinhVien));
            }
        }

        // Lấy tổng số sách đang được mượn
        String query2 = "SELECT COUNT(*) AS total FROM phieumuon WHERE trangthaimuon = 'DangMuon'";
        try (Statement statement = connection.createStatement();
             ResultSet resultSet2 = statement.executeQuery(query2)) {
            // Xử lý kết quả
            if (resultSet2.next()) {
                int totalSachMuon = resultSet2.getInt("total");
                txtTsm.setText(Integer.toString(totalSachMuon));
            }
        }

        // Lấy tổng số sách
        String query3 = "SELECT COUNT(*) AS total FROM sach";
        try (Statement statement = connection.createStatement();
             ResultSet resultSet3 = statement.executeQuery(query3)) {
            // Xử lý kết quả
            if (resultSet3.next()) {
                int totalSach = resultSet3.getInt("total");
                txtTst.setText(Integer.toString(totalSach));
            }
        }

        // Lấy tổng số lượng sách
        String query4 = "SELECT SUM(soluong) AS total FROM sach";
        try (Statement statement = connection.createStatement();
             ResultSet resultSet4 = statement.executeQuery(query4)) {
            // Xử lý kết quả
            if (resultSet4.next()) {
                int totalSach = resultSet4.getInt("total");
                txtTslc.setText(Integer.toString(totalSach));
            }
        }

        java.util.Date currentDate = new java.util.Date(); // Lấy ngày hiện tại
        java.sql.Date sqlCurrentDate = new java.sql.Date(currentDate.getTime()); // Chuyển đổi sang kiểu java.sql.Date

        // Lấy tổng số sách được mượn trong ngày
        String query5 = "SELECT COUNT(*) AS total FROM phieumuon WHERE ngaymuon = ?";
        try (PreparedStatement preparedStatement5 = connection.prepareStatement(query5)) {
            preparedStatement5.setDate(1, sqlCurrentDate);
            try (ResultSet resultSet5 = preparedStatement5.executeQuery()) {
                // Xử lý kết quả
                if (resultSet5.next()) {
                    int totalMuonTrongNgay = resultSet5.getInt("total");
                    txtMtn.setText(Integer.toString(totalMuonTrongNgay));
                }
            }
        }

        // Lấy tổng số sách được trả trong ngày
        String query6 = "SELECT COUNT(*) AS total FROM phieumuon WHERE ngaytra = ?";
        try (PreparedStatement preparedStatement6 = connection.prepareStatement(query6)) {
            preparedStatement6.setDate(1, sqlCurrentDate);
            try (ResultSet resultSet6 = preparedStatement6.executeQuery()) {
                // Xử lý kết quả
                if (resultSet6.next()) {
                    int totalSachTraTrongNgay = resultSet6.getInt("total");
                    txtTsstn.setText(Integer.toString(totalSachTraTrongNgay));
                }
            }
        }

        // Lấy tổng số sách đã được cho mượn trong 30 ngày gần nhất
        String query7 = "SELECT COUNT(*) AS total FROM phieumuon WHERE ngaymuon >= DATE_SUB(NOW(), INTERVAL 30 DAY)";
        try (Statement statement = connection.createStatement();
             ResultSet resultSet7 = statement.executeQuery(query7)) {
            // Xử lý kết quả
            if (resultSet7.next()) {
                int totalSachMuon30Ngay = resultSet7.getInt("total");
                txtM1t.setText(Integer.toString(totalSachMuon30Ngay));
            }
        }

        // Lấy tổng số sách đã trả trong 30 ngày gần nhất
        String query8 = "SELECT COUNT(*) AS total FROM phieumuon WHERE ngaytra >= DATE_SUB(NOW(), INTERVAL 30 DAY)";
        try (Statement statement = connection.createStatement();
             ResultSet resultSet8 = statement.executeQuery(query8)) {
            // Xử lý kết quả
            if (resultSet8.next()) {
                int totalSachTra30Ngay = resultSet8.getInt("total");
                txtT1t.setText(Integer.toString(totalSachTra30Ngay));
            }
        }

        // Lấy tổng số phiếu quá hạn trả
        String query = "SELECT COUNT(*) AS total FROM phieumuon WHERE ngayphaitra < NOW() AND ngaytra IS NULL";
        try (Statement statement = connection.createStatement();
             ResultSet resultSet = statement.executeQuery(query)) {
            // Xử lý kết quả
            if (resultSet.next()) {
                int tongSoPhieuQuaHan = resultSet.getInt("total");
                // Gán giá trị vào thành phần giao diện txtquahan
                txtquahan.setText(Integer.toString(tongSoPhieuQuaHan));
            }
        }

        // Đóng kết nối
        connection.close();
    } catch (SQLException ex) {
        ex.printStackTrace();
    }
    }//GEN-LAST:event_btn_thongkeActionPerformed

    private void txtTsmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTsmActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTsmActionPerformed

    private void txtTsdgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTsdgActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTsdgActionPerformed

    private void txtTstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTstActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTstActionPerformed

    private void btntim3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btntim3ActionPerformed
        // TODO add your handling code here:
        String input = JOptionPane.showInputDialog(this, "Nhập mã sinh viên để tìm kiếm");
        if(input != null && input.length()>0){
            phieumuonList = PhieumuonModify.findByFullnameAndStatus(input);
            model2.setRowCount(0);
            if (phieumuonList.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Không tìm thấy sách");
                showPhieumuon(); // Hiển thị lại toàn bộ danh sách sinh viên
            } else {
                model2.setRowCount(0);
                for (Phieumuon phieumuon : phieumuonList) {
                    Sinhvien sinhvien = SinhvienModify.findSinhvienById(phieumuon.getMsv_muon());
                    Sach sach = SachModify.findSachById(phieumuon.getId_sach());
                    model2.addRow(new Object[]{
                        model2.getRowCount() + 1,
                        phieumuon.getMaphieumuon(),
                        phieumuon.getMsv_muon(),
                        sinhvien.getTensv(),
                        phieumuon.getId_sach(),
                        sach.getTensach(),
                        phieumuon.getNgaymuon(),
                        phieumuon.getNgaytra(),
                        phieumuon.getTrangthaimuon()
                    });
                }
            }
        }else{
            showPhieumuon();
        }
    }//GEN-LAST:event_btntim3ActionPerformed

    private void btnTrasachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTrasachActionPerformed
        // TODO add your handling code here:
        int selectedIndex = hienthi3.getSelectedRow();
        if (selectedIndex >= 0) {
            Phieumuon std = phieumuonList.get(selectedIndex);
            int old_id_sach = std.getId_sach();

            // Kiểm tra xem sinh viên đã mượn sách mới hay chưa

            int option = JOptionPane.showConfirmDialog(this, "Bạn chắc chắn muốn lưu và cập nhật dữ liệu?");
            if (option == JOptionPane.YES_OPTION) {
                std.setTrangthaimuon("DaTra");

                // Tăng số lượng sách của id_sach cũ lên 1
                SachModify.increaseQuantity(old_id_sach);
            }

            PhieumuonModify.updatetra(std);

            showPhieumuon();
            showSach();
            // Đặt các trường về giá trị mặc định sau khi lưu thành công (tuỳ vào yêu cầu của bạn)
            txtMsvm.setText("");
            txtMsm.setText("");

        }
    }//GEN-LAST:event_btnTrasachActionPerformed

    private void btnxoa3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnxoa3ActionPerformed
        // TODO add your handling code here:
        int selectedIndex = hienthi3.getSelectedRow();
        if (selectedIndex >= 0) {
            Phieumuon std = phieumuonList.get(selectedIndex);
            int option = JOptionPane.showConfirmDialog(this, "Bạn chắc chắn muốn xóa dữ liệu này?");
            System.out.println("option: " + option);
            if (option == 0) {
                int id_sach = std.getId_sach();
                PhieumuonModify.delete(std.getMaphieumuon());
                SachModify.increaseQuantity(id_sach);
                showPhieumuon();
                showSach();
            }
        }
    }//GEN-LAST:event_btnxoa3ActionPerformed

    private void btnluu3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnluu3ActionPerformed
        // TODO add your handling code here:
        String msv_muon = txtMsvm.getText();
        int new_id_sach = Integer.parseInt(txtMsm.getText());
        String trangthaimuon = "DangMuon";

        int selectedIndex = hienthi3.getSelectedRow();
        if (selectedIndex >= 0) {
            Phieumuon std = phieumuonList.get(selectedIndex);
            int old_id_sach = std.getId_sach();
            String old_msv_muon = std.getMsv_muon();
            String old_trangthaimuon = std.getTrangthaimuon();

            boolean foundMatch = false;

            for (Phieumuon pm : phieumuonList) {
                if (pm.getMsv_muon().equals(msv_muon) && pm.getId_sach() == new_id_sach && pm.getTrangthaimuon().equals(trangthaimuon)) {
                    foundMatch = true;
                    break;
                }
            }

            if (foundMatch) {
                JOptionPane.showMessageDialog(this, "Bạn đang mượn sách này. Không thể sửa phiếu mượn.");
            } else {
                int option = JOptionPane.showConfirmDialog(this, "Bạn chắc chắn muốn lưu và cập nhật dữ liệu?");
                if (option == JOptionPane.YES_OPTION) {
                    if (new_id_sach != old_id_sach) {
                        // Tăng số lượng sách của id_sach cũ lên 1
                        SachModify.increaseQuantity(old_id_sach);
                        // Giảm số lượng sách của id_sach mới đi 1
                        SachModify.decreaseQuantity(new_id_sach);
                    }

                    std.setMsv_muon(msv_muon);
                    std.setId_sach(new_id_sach);

                    PhieumuonModify.update(std);

                    showPhieumuon();
                    showSach();
                    // Đặt các trường về giá trị mặc định sau khi lưu thành công (tuỳ vào yêu cầu của bạn)
                    txtMsvm.setText("");
                    txtMsm.setText("");

                }
            }
        }
    }//GEN-LAST:event_btnluu3ActionPerformed

    private void btnsua3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsua3ActionPerformed
        // TODO add your handling code here:
        int selectedIndex = hienthi3.getSelectedRow();
        if (selectedIndex >= 0) {
            Phieumuon std = phieumuonList.get(selectedIndex);

            int option = JOptionPane.showConfirmDialog(this, "Bạn muốn chọn dữ liệu này để sửa?");
            System.out.println("option: " + option);
            if (option == JOptionPane.YES_OPTION) {
                txtMsvm.setText(std.getMsv_muon());
                txtMsm.setText(Integer.toString(std.getId_sach()));

            }
        }
    }//GEN-LAST:event_btnsua3ActionPerformed

    private void btnthem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnthem3ActionPerformed

        // TODO add your handling code here:
        String msv_muon = txtMsvm.getText();
        int id_sach = Integer.parseInt(txtMsm.getText());

        Sach sach = SachModify.findSachById(id_sach);
        Sinhvien sv = SinhvienModify.findSinhvienById(msv_muon);

        if (sach == null) {
            JOptionPane.showMessageDialog(this, "Sách không tồn tại");
        } else if (sv == null) {
            JOptionPane.showMessageDialog(this, "Mã sinh viên không tồn tại");
        } else if (sach.getSoluong() == 0) {
            JOptionPane.showMessageDialog(this, "Số lượng sách đã hết");
        } else {
            boolean isDangMuon = PhieumuonModify.isStatusDangMuon(msv_muon, id_sach);

            if (isDangMuon) {
                JOptionPane.showMessageDialog(this, "Sách đã được mượn, không thể mượn tiếp");
            } else {
                String trangthaimuon = "DangMuon";
                LocalDate currentDate = LocalDate.now();
                Date ngaymuon = Date.valueOf(currentDate);

                // Kiểm tra xem đã tồn tại phiếu mượn trùng msv_muon, id_sach và trangthaimuon "DangMuon" chưa
                boolean isExistingLoan = PhieumuonModify.checkExistingLoan1(msv_muon, id_sach, trangthaimuon);

                if (isExistingLoan) {
                    JOptionPane.showMessageDialog(this, "Bạn đang mượn sách này, không thể mượn tiếp");
                } else {
                    boolean isInserted = PhieumuonModify.insert(msv_muon, id_sach, ngaymuon, trangthaimuon);

                    if (isInserted) {
                        // Giảm số lượng sách đi 1
                        sach.setSoluong(sach.getSoluong() - 1);
                        SachModify.update(sach);
                        showSach();
                        showPhieumuon();
                        txtMsvm.setText("");
                        txtMsm.setText("");
                    } else {
                        JOptionPane.showMessageDialog(this, "Không thể thêm phiếu mượn");
                    }
                }
            }
        }
    }//GEN-LAST:event_btnthem3ActionPerformed

    private void txtMsvmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMsvmActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMsvmActionPerformed

    private void btnTim1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTim1ActionPerformed
        // TODO add your handling code here:
        String input = JOptionPane.showInputDialog(this, "Nhập tên sách để tìm kiếm");
        if(input != null && input.length()>0){
            sachList = SachModify.findByFullname(input);
            model.setRowCount(0);
            if (sachList.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Không tìm thấy sách");
                showSach(); // Hiển thị lại toàn bộ danh sách sinh viên
            } else {
                model.setRowCount(0);
                for (Sach sach : sachList) {
                    model.addRow(new Object[] {
                        hienthi.getRowCount() + 1,
                        sach.getId(),
                        sach.getTensach(),
                        sach.getTacgia(),
                        sach.getTheloai(),
                        sach.getSoluong()
                    });
                }
            }
        }else{
            showSach();
        }
    }//GEN-LAST:event_btnTim1ActionPerformed

    private void btnHuy1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHuy1ActionPerformed
        // TODO add your handling code here:
        txtTensach.setText("");
        txtTacgia.setText("");
        txtTheloai.setText("");
        txtSoluong.setText("");

    }//GEN-LAST:event_btnHuy1ActionPerformed

    private void btnXoa1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoa1ActionPerformed
        // TODO add your handling code here:
        int selectedIndex = hienthi.getSelectedRow();
        if(selectedIndex >=0){
            Sach std = sachList.get(selectedIndex);
            int option = JOptionPane.showConfirmDialog(this, "bạn chắc chắn muốn xóa dữ liệu này?");
            System.out.println("option:" + option);
            if(option == 0) {
                SachModify.delete(std.getId());
                showSach();
            }
        }
    }//GEN-LAST:event_btnXoa1ActionPerformed

    private void btnLuu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLuu1ActionPerformed
        // TODO add your handling code here:
        String tensach = txtTensach.getText();
        int soluong = Integer.parseInt(txtSoluong.getText());
        String tacgia = txtTacgia.getText();
        String theloai = txtTheloai.getText();

        int selectedIndex = hienthi.getSelectedRow();
        if (selectedIndex >= 0) {
            Sach std = sachList.get(selectedIndex);
            std.setTensach(tensach);
            std.setSoluong(soluong);
            std.setTacgia(tacgia);
            std.setTheloai(theloai);

            int option = JOptionPane.showConfirmDialog(this, "Bạn chắc chắn muốn lưu và cập nhật dữ liệu?");
            if (option == JOptionPane.YES_OPTION) {
                SachModify.update(std);
                showSach();
                // Đặt các trường về giá trị mặc định sau khi lưu thành công (tuỳ vào yêu cầu của bạn)
                txtTensach.setText("");
                txtTacgia.setText("");
                txtTheloai.setText("");
                txtSoluong.setText("");
            }
        }
    }//GEN-LAST:event_btnLuu1ActionPerformed

    private void btnSua1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSua1ActionPerformed
        // TODO add your handling code here:
        int selectedIndex = hienthi.getSelectedRow();
        if (selectedIndex >= 0) {
            Sach std = sachList.get(selectedIndex);

            int option = JOptionPane.showConfirmDialog(this, "Bạn muốn chọn dữ liệu này để sửa?");
            System.out.println("option: " + option);
            if (option == JOptionPane.YES_OPTION) {
                txtTensach.setText(std.getTensach());
                txtTacgia.setText(std.getTacgia());
                txtTheloai.setText(std.getTheloai());
                txtSoluong.setText(String.valueOf(std.getSoluong()));
            }
        }
    }//GEN-LAST:event_btnSua1ActionPerformed

    private void btnThem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThem1ActionPerformed
        // TODO add your handling code here:
        String tensach = txtTensach.getText();
        int soluong = Integer.parseInt(txtSoluong.getText());
        String tacgia = txtTacgia.getText();
        String theloai = txtTheloai.getText();

        Sach std = new Sach(tensach, tacgia, theloai, soluong);

        SachModify.insert(std);
        showSach();
    }//GEN-LAST:event_btnThem1ActionPerformed

    private void btntim2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btntim2ActionPerformed
        // TODO add your handling code here:
        String input = JOptionPane.showInputDialog(this, "Nhập tên sinh viên để tìm");
        if(input != null && input.length()>0){
            sinhvienList = SinhvienModify.findByFullname(input);
            model1.setRowCount(0);
            if (sinhvienList.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Không tìm thấy sinh viên");
                showSinhvien(); // Hiển thị lại toàn bộ danh sách sinh viên
            } else {
                model1.setRowCount(0);
                for (Sinhvien sv : sinhvienList) {
                    model1.addRow(new Object[] {
                        hienthi.getRowCount() + 1,
                        sv.getMsv(),
                        sv.getTensv(),
                        sv.getDiachi(),
                        sv.getSdt(),
                        sv.getEmail()
                    });
                }
            }
        }else{
            showSinhvien();
        }
    }//GEN-LAST:event_btntim2ActionPerformed

    private void btnHuy4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHuy4ActionPerformed
        // TODO add your handling code here:
        txtMsv.setText("");
        txtTensv.setText("");
        txtDiachi.setText("");
        txtSdt.setText("");
        txtEmail.setText("");
    }//GEN-LAST:event_btnHuy4ActionPerformed

    private void btnXoa4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoa4ActionPerformed
        // TODO add your handling code here:
        int selectedIndex = hienthi2.getSelectedRow();
        if(selectedIndex >=0){
            Sinhvien std = sinhvienList.get(selectedIndex);
            int option = JOptionPane.showConfirmDialog(this, "do you want to delete this item?");
            System.out.println("option:" + option);
            if(option == 0) {
                SinhvienModify.delete(std.getMsv());
                showSinhvien();
            }
        }
    }//GEN-LAST:event_btnXoa4ActionPerformed

    private void btnLuu4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLuu4ActionPerformed
        // TODO add your handling code here:

        String tensv = txtTensv.getText();
        String diachi = txtDiachi.getText();
        String sdt = txtSdt.getText();
        String email = txtEmail.getText();

        int selectedIndex = hienthi2.getSelectedRow();
        if (selectedIndex >= 0) {
            Sinhvien std = sinhvienList.get(selectedIndex);
            std.setTensv(tensv);
            std.setDiachi(diachi);
            std.setSdt(sdt);
            std.setEmail(email);

            int option = JOptionPane.showConfirmDialog(this, "Bạn chắc chắn muốn lưu và cập nhật dữ liệu?");
            if (option == JOptionPane.YES_OPTION) {
                SinhvienModify.update(std);
                showSinhvien();
                // Đặt các trường về giá trị mặc định sau khi lưu thành công (tuỳ vào yêu cầu của bạn)
                txtMsv.setText("");
                txtTensv.setText("");
                txtDiachi.setText("");
                txtSdt.setText("");
                txtEmail.setText("");
            }
        }
    }//GEN-LAST:event_btnLuu4ActionPerformed

    private void btnSua4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSua4ActionPerformed
        // TODO add your handling code here:
        int selectedIndex = hienthi2.getSelectedRow();
        if (selectedIndex >= 0) {
            Sinhvien std = sinhvienList.get(selectedIndex);

            int option = JOptionPane.showConfirmDialog(this, "Bạn muốn chọn dữ liệu này để sửa?");
            System.out.println("option: " + option);
            if (option == JOptionPane.YES_OPTION) {
                txtMsv.setText(std.getMsv());
                txtTensv.setText(std.getTensv());
                txtDiachi.setText(std.getDiachi());
                txtSdt.setText(std.getSdt());
                txtEmail.setText(std.getEmail());

                // Vô hiệu hóa ô nhập văn bản txtMsv
                txtMsv.setEnabled(false);
            }
        }
    }//GEN-LAST:event_btnSua4ActionPerformed

    private void btnThem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThem4ActionPerformed
        // TODO add your handling code here:
        //         String msv = txtMsv.getText();
        //         String tensv = txtTensv.getText();
        //         String diachi = txtDiachi.getText();
        //         String sdt = txtSdt.getText();
        //         String email = txtEmail.getText();
        //        Sinhvien std = new Sinhvien(msv, tensv, diachi, sdt, email);
        //        SinhvienModify.insert(std);
        //        showSinhvien();

        String msv = txtMsv.getText();
        String tensv = txtTensv.getText();
        String diachi = txtDiachi.getText();
        String sdt = txtSdt.getText();
        String email = txtEmail.getText();

        // Kiểm tra msv đã tồn tại hay chưa
        if (SinhvienModify.isMsvExists(msv)) {
            JOptionPane.showMessageDialog(this, "MSV đã tồn tại trong cơ sở dữ liệu.");
        } else {
            Sinhvien std = new Sinhvien(msv, tensv, diachi, sdt, email);
            SinhvienModify.insert(std);
            showSinhvien();
        }

    }//GEN-LAST:event_btnThem4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(quanlithuvienap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(quanlithuvienap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(quanlithuvienap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(quanlithuvienap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new quanlithuvienap().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHuy1;
    private javax.swing.JButton btnHuy4;
    private javax.swing.JButton btnLuu1;
    private javax.swing.JButton btnLuu4;
    private javax.swing.JButton btnSua1;
    private javax.swing.JButton btnSua4;
    private javax.swing.JButton btnThem1;
    private javax.swing.JButton btnThem4;
    private javax.swing.JButton btnTim1;
    private javax.swing.JButton btnTrasach;
    private javax.swing.JButton btnXoa1;
    private javax.swing.JButton btnXoa4;
    private javax.swing.JButton btn_thongke;
    private javax.swing.JButton btnluu3;
    private javax.swing.JButton btnsua3;
    private javax.swing.JButton btnthem3;
    private javax.swing.JButton btntim2;
    private javax.swing.JButton btntim3;
    private javax.swing.JButton btnxoa3;
    private javax.swing.JTable hienthi;
    private javax.swing.JTable hienthi2;
    private javax.swing.JTable hienthi3;
    private javax.swing.JTabbedPane hienthibandoc;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTextField txtDiachi;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtM1t;
    private javax.swing.JTextField txtMsm;
    private javax.swing.JTextField txtMsv;
    private javax.swing.JTextField txtMsvm;
    private javax.swing.JTextField txtMtn;
    private javax.swing.JTextField txtSdt;
    private javax.swing.JTextField txtSoluong;
    private javax.swing.JTextField txtT1t;
    private javax.swing.JTextField txtTacgia;
    private javax.swing.JTextField txtTensach;
    private javax.swing.JTextField txtTensv;
    private javax.swing.JTextField txtTheloai;
    private javax.swing.JTextField txtTsdg;
    private javax.swing.JTextField txtTslc;
    private javax.swing.JTextField txtTsm;
    private javax.swing.JTextField txtTsstn;
    private javax.swing.JTextField txtTst;
    private javax.swing.JTextField txtquahan;
    // End of variables declaration//GEN-END:variables
}
